const PDFDocument = require("pdfkit");

/**
 * Generate a usage rights document for a project (plain text for DB storage).
 */
function generateUsageRightsDoc({ businessName, contentType, usageRights, timeline }) {
  const brand = businessName || "Brand";
  const rights = usageRights || "Organic social + in-store, 12 months";
  const timing = timeline || "Standard timeline";
  return [
    `Usage Rights Agreement`,
    `Brand: ${brand}`,
    `Content Type: ${contentType || "UGC content"}`,
    `Rights: ${rights}`,
    `Timeline: ${timing}`,
    `This agreement grants the brand non-exclusive usage rights as specified above.`,
  ].join("\n");
}

/**
 * Generate a formatted PDF usage rights document. Returns a Buffer.
 */
function generateUsageRightsPDF({
  businessName,
  contentType,
  usageRights,
  timeline,
  creatorName,
  deliverables,
  compensationType,
  compensationDetails,
}) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: 60 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const brand = businessName || "Brand";
    const rights = usageRights || "Organic social + in-store, 12 months";
    const timing = timeline || "Standard timeline";
    const creator = creatorName || "Creator";
    const content = contentType || "UGC content";
    const deliv = deliverables || "As agreed";
    const today = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    // Title
    doc.fontSize(22).font("Helvetica-Bold").text("Content Usage Rights Agreement", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).font("Helvetica").fillColor("#666").text(`Generated on ${today}`, { align: "center" });
    doc.moveDown(1.5);

    // Divider
    doc.strokeColor("#cccccc").lineWidth(0.5).moveTo(60, doc.y).lineTo(552, doc.y).stroke();
    doc.moveDown(1);

    // Section helper
    const section = (title, body) => {
      doc.fontSize(13).font("Helvetica-Bold").fillColor("#222").text(title);
      doc.moveDown(0.3);
      doc.fontSize(10.5).font("Helvetica").fillColor("#444").text(body);
      doc.moveDown(1);
    };

    // 1. Parties
    section("1. Parties", `This agreement is entered into between:\n\nBrand: ${brand}\nCreator: ${creator}`);

    // 2. Content Scope
    section("2. Content Scope", `Content Type: ${content}\nDeliverables: ${deliv}`);

    // 3. Rights Granted
    section(
      "3. Rights Granted",
      `The Brand is granted non-exclusive usage rights for the content described above.\n\nScope: ${rights}\n\nThe Creator retains original ownership of the content and may use it in their personal portfolio.`
    );

    // 4. Timeline
    section("4. Timeline", `Delivery Timeline: ${timing}`);

    // 5. Compensation
    let compText = compensationType || "FLAT_FEE";
    if (compensationDetails?.note) {
      compText += ` — ${compensationDetails.note}`;
    }
    section("5. Compensation", `Type: ${compText}\n\nPayment terms as agreed between parties through the Locale platform.`);

    // 6. General Terms
    section(
      "6. General Terms",
      "a) The Brand shall not transfer these usage rights to third parties without written consent.\nb) The Creator warrants that the content is original work.\nc) Either party may terminate this agreement with 30 days written notice.\nd) This agreement is governed by the laws of the State of Illinois."
    );

    // Signature lines
    doc.moveDown(1);
    doc.strokeColor("#cccccc").lineWidth(0.5).moveTo(60, doc.y).lineTo(552, doc.y).stroke();
    doc.moveDown(1.5);

    doc.fontSize(11).font("Helvetica-Bold").fillColor("#222").text("Signatures");
    doc.moveDown(1);

    const sigY = doc.y;
    doc.fontSize(10).font("Helvetica").fillColor("#444");
    doc.text("Brand Representative:", 60, sigY);
    doc.text("________________________", 60, sigY + 20);
    doc.text(brand, 60, sigY + 38);

    doc.text("Creator:", 320, sigY);
    doc.text("________________________", 320, sigY + 20);
    doc.text(creator, 320, sigY + 38);

    doc.moveDown(4);
    doc.fontSize(8).fillColor("#999").text("Generated by Locale — hyperlocal UGC sourcing platform", { align: "center" });

    doc.end();
  });
}

module.exports = { generateUsageRightsDoc, generateUsageRightsPDF };
